// (c) by Stefan Roettger, licensed under MIT license

WGL_MACRO(glBlendEquation,GLBLENDEQUATION)

WGL_MACRO(glActiveTexture,GLACTIVETEXTURE)
WGL_MACRO(glTexImage3D,GLTEXIMAGE3D)

WGL_MACRO(glGenVertexArrays,GLGENVERTEXARRAYS)
WGL_MACRO(glBindVertexArray,GLBINDVERTEXARRAY)
WGL_MACRO(glDeleteVertexArrays,GLDELETEVERTEXARRAYS)

WGL_MACRO(glGenBuffers,GLGENBUFFERS)
WGL_MACRO(glBindBuffer,GLBINDBUFFER)
WGL_MACRO(glBufferData,GLBUFFERDATA)
WGL_MACRO(glDeleteBuffers,GLDELETEBUFFERS)

WGL_MACRO(glVertexAttribPointer,GLVERTEXATTRIBPOINTER)
WGL_MACRO(glEnableVertexAttribArray,GLENABLEVERTEXATTRIBARRAY)
WGL_MACRO(glDisableVertexAttribArray,GLDISABLEVERTEXATTRIBARRAY)

WGL_MACRO(glCreateShader,GLCREATESHADER)
WGL_MACRO(glShaderSource,GLSHADERSOURCE)
WGL_MACRO(glCompileShader,GLCOMPILESHADER)
WGL_MACRO(glGetShaderiv,GLGETSHADERIV)
WGL_MACRO(glGetShaderInfoLog,GLGETSHADERINFOLOG)
WGL_MACRO(glDetachShader,GLDETACHSHADER)
WGL_MACRO(glDeleteShader,GLDELETESHADER)

WGL_MACRO(glCreateProgram,GLCREATEPROGRAM)
WGL_MACRO(glAttachShader,GLATTACHSHADER)
WGL_MACRO(glBindAttribLocation,GLBINDATTRIBLOCATION)
WGL_MACRO(glLinkProgram,GLLINKPROGRAM)
WGL_MACRO(glGetProgramiv,GLGETPROGRAMIV)
WGL_MACRO(glGetProgramInfoLog,GLGETPROGRAMINFOLOG)
WGL_MACRO(glDeleteProgram,GLDELETEPROGRAM)

WGL_MACRO(glUseProgram,GLUSEPROGRAM)
WGL_MACRO(glGetUniformLocation,GLGETUNIFORMLOCATION)

WGL_MACRO(glUniform1i,GLUNIFORM1I)
WGL_MACRO(glUniform1f,GLUNIFORM1F)
WGL_MACRO(glUniform2fv,GLUNIFORM2FV)
WGL_MACRO(glUniform3fv,GLUNIFORM3FV)
WGL_MACRO(glUniform4fv,GLUNIFORM4FV)
WGL_MACRO(glUniformMatrix2fv,GLUNIFORMMATRIX2FV)
WGL_MACRO(glUniformMatrix3fv,GLUNIFORMMATRIX3FV)
WGL_MACRO(glUniformMatrix4fv,GLUNIFORMMATRIX4FV)
