// (c) by Stefan Roettger, licensed under MIT license

#ifndef GL_TEXTURE_MAX_ANISOTROPY_EXT
#   define GL_TEXTURE_MAX_ANISOTROPY_EXT GL_TEXTURE_MAX_ANISOTROPY
#endif
#ifndef GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT
#   define GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT GL_MAX_TEXTURE_MAX_ANISOTROPY
#endif

#if (LGL_OPENGL_VERSION>=30 || defined(LGL_GLES3))
#   define GLVERTEX_TEXTURE_SWIZZLE
#   ifndef GL_TEXTURE_SWIZZLE_RGBA
#      undef GLVERTEX_TEXTURE_SWIZZLE
#   endif
#endif
